[colors.primary]
background = '#19120c'
foreground = '#efe0d5'

[colors.selection]
text = '#efe0d5'
background = '#6a3b02'

[colors.cursor]
text = '#19120c'
cursor = '#feb876'

[colors.normal]
black   = '#19120c'
red     = '#e2497e'
green   = '#97d66e'
yellow  = '#dbad7b'
blue    = '#bb6f28'
magenta = '#be946c'
cyan    = '#feb876'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f8f'
green   = '#a9e086'
yellow  = '#e8c297'
blue    = '#ffc88f'
magenta = '#b26544'
cyan    = '#967441'
white   = '#ffffff'
